routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\InventoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landingpage');
});

Route::group([
    'prefix' => 'category',
    'as' => 'category.',
], function () {
    Route::get('/', [CategoryController::class, 'index'])->name('index');
    Route::get('/create', [CategoryController::class, 'create'])->name('create');
    Route::post('/store', [CategoryController::class, 'store'])->name('store');
    Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
    Route::post('/{id}/update', [CategoryController::class, 'update'])->name('update');
    Route::get('/{id}/delete', [CategoryController::class, 'delete'])->name('delete');
});

Route::group([
    'prefix' => 'inventory',
    'as' => 'inventory.',
], function () {
    Route::get('/', [InventoryController::class, 'index'])->name('index');
    Route::get('/create', [InventoryController::class, 'create'])->name('create');
    Route::post('/store', [InventoryController::class, 'store'])->name('store');
    Route::get('/{id}/edit', [InventoryController::class, 'edit'])->name('edit');
    Route::post('/{id}/update', [InventoryController::class, 'update'])->name('update');
    Route::get('/{id}/delete', [InventoryController::class, 'delete'])->name('delete');
});

Route::get('/latest-ending-stock', [InventoryController::class, 'getLatestInventoryStock']);

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;

    protected $primaryKey = 'inventory_code';

    protected $fillable = ['good', 'price', 'category_code', 'stock'];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_code');
    }

    public function stock_histories()
    {
        return $this->hasMany(StockHistory::class);
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\InventoriyRequest;
use App\Models\Category;
use App\Models\Inventory;
use App\Models\StockHistory;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class InventoryController extends Controller
{
    private $minimumPriceToBeDiscounted = 40000;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Inventory::join('categories', 'categories.category_code', 'inventories.category_code')->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '<a href="javascript:void(0)" class="text-black" id="editInventory" data-bs-toggle="modal" data-bs-target="#inventory" data-id="' . $row->inventory_code . '" onclick="editInventory(' . $row->inventory_code . ')">Edit</a> | <a href="javascript:void(0)" data-id="' . $row->inventory_code . '" class="text-black" id="deleteInventory" onclick="deleteInventory(' . $row->inventory_code . ')">Delete</a>';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        $categories = Category::all();

        return view('inventory.index', compact('latestInventoryStock', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('inventory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(InventoriyRequest $request)
    {
        $validatedData = $request->validated();

        if ($validatedData['price'] > $this->minimumPriceToBeDiscounted) ($validatedData['price'] * 10) / 100;
        if (Inventory::where('good', $validatedData['good'])->exists()) {
            return response()->json([
                'success' => false,
                'message' => 'Inventory already exists.'
            ]);
        }

        Inventory::create($validatedData);

        return response()->json([
            'success' => true,
            'message' => 'Inventory stored successfully',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $inventory = Inventory::findOrFail($id);

        return response()->json([
            'success' => true,
            'inventory' => $inventory,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(InventoriyRequest $request, $id)
    {
        $validatedData = $request->validated();

        $inventory = Inventory::findOrFail($id);

        $inventory->update($validatedData);

        return response()->json([
            'success' => true,
            'message' => 'Inventory updated successfully',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $inventory = Inventory::findOrFail($id);

        $inventory->delete();

        return response()->json([
            'success' => true,
            'message' => 'Inventory deleted successfully',
        ]);
    }

    /**
     * Retrieve latest stock history for each inventory item for a day.
     *
     * @return \Illuminate\Http\Response
     */
    public function getLatestInventoryStock()
    {
        $latestInventory = StockHistory::select('inventory_code', DB::raw('SUM(final_stock) as final_stock'))->where('date', Carbon::now())->groupBy('inventory_code')->get();

        // $latestInventory = DB::raw('select inventory_code, final_stock, max(date) as max_date from stock_histories group by inventory_code) as latest_stock where latest_stock.inventory_code = stock_histories.inventory_code and latest_stock.max_date = stock_histories.date');

        return response()->json($latestInventory);
    }
}

resources/views/inventory/index.blade.php
@extends('app')

@section('content')
	<div class="row">
		<div class="col-sm-12">
			<button type="button" class="btn btn-primary float-end mb-5" id="createInventory" data-bs-toggle="modal"
				data-bs-target="#inventory" onclick="createInventory()">
				Insert New Item
			</button>

			<table class="table" id="inventoryTable">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col">Goods</th>
						<th scope="col">Category</th>
						<th scope="col">Price</th>
						<th scope="col">action</th>
					</tr>
				</thead>
				<tbody>

				</tbody>
			</table>
		</div>
	</div>

	{{-- modal --}}
	<!-- Modal -->
	<div class="modal fade" id="inventory" tabindex="-1" aria-labelledby="inventoryLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="inventoryLabel">Insert Inventory</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<form action="{{ route('inventory.store') }}" method="post" id="inventoryForm">
						@csrf
						<div class="mb-3">
							<label for="good" class="form-label">Good</label>
							<input type="text" name="good" class="form-control" id="good" autofocus required>
						</div>
						<div class="mb-3">
							<label for="price" class="form-label">Price</label>
							<input type="text" name="price" class="form-control" id="price" required>
						</div>
						<div class="mb-3">
							<label for="category_code" class="form-label">Category</label>
							<select name="category_code" id="category_code" class="form-control" required>
								@isset($categories)
									@foreach ($categories as $category)
										<option value="{{ $category->category_code }}">{{ $category->category }}</option>
									@endforeach
								@endisset
							</select>
						</div>
						<div class="mb-3">
							<label for="stock" class="form-label">Stock</label>
							<input type="text" name="stock" class="form-control" id="stock" required>
						</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-primary">Save changes</button>
				</div>
				</form>
			</div>
		</div>
	</div>
@endsection

@section('page_scripts')
	<script>
	 $(document).ready(function() {
	  var columns = [{
	    data: 'DT_RowIndex',
	    orderable: false,
	    searchable: false,
	   },
	   {
	    data: 'good',
	    name: 'good'
	   }, {
	    data: 'category',
	    name: 'category'
	   }, {
	    data: 'price',
	    name: 'price'
	   }, {
	    data: 'action',
	    name: 'action',
	    orderable: false,
	    searchable: false,
	   },
	  ]
	  var table = initiateDatatable('inventoryTable', "{{ route('inventory.index') }}", columns);

	  $('#inventoryForm').submit(function(e) {
	   e.preventDefault();
	   var form = $(this);
	   var url = form.attr('action');
	   var method = form.attr('method');
	   var data = form.serialize();
	   $.ajax({
	    url: url,
	    method: method,
	    data: data,
	    success: function(data) {
	     $('#inventory').modal('hide');
	     //  table.ajax.reload();
	     table.draw();
	    }
	   });
	  })
	 })
	</script>
@endsection